sudo: false
language: scala
scala:
- "2.11.7"
script:
  - sbt clean coverage testsJVM/test
after_success:
  - pip install --user codecov && codecov
branches:
  only:
    - master
cache:
  directories:
    $HOME/.ivy2/cache
